<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <AssemblyName>Kyra.Core</AssemblyName>
    <Product>Kyra.Core</Product>
    <Company>Kyra</Company>
  </PropertyGroup>

</Project>
